### ISSUE TITLE
Doesn't push

### ISSUE THREAD

**Issue by Dymaxion00** [funkjedi/PinboardPush#1]
Hi!  I know this is ancient code, but I was really hoping to use it.  It seems the version in the web store doesn't work, at least on Chrome 68 and 2018-era pinboard.  Any chance you could take a look at it?

**Comment by funkjedi** [comment]
Just refactored and published an update. Should be live in the web store shortly.

**Comment by Dymaxion00** [comment]
Works!  Thanks a ton, this solves a real problem for me.
